import { imagen1, imagen2, imagen3, imagen4, imagen5, imagen6, imagen7 } from "../helpers/Index";

export const mockData = [
  {
    id: 1,
    image: imagen1,
    title: "Micro Amd Ryzen 7 5700g 4.6 Ghz Am4",
    price: 155.200
  },
  {
    id: 2,
    image: imagen2,
    title: "Micro Intel I9-11700kf 5.0ghz 16mb s.1200",
    price: 221.674
  },
  {
    id: 3,
    image: imagen3,
    title: "Micro Amd Ryzen 9 5900x 4.8 Ghz Am4",
    price: 295.000
  },
  {
    id: 4,
    image: imagen4,
    title: "Monitor LED CURVO 24 Samsung",
    price: 108.823
  },
  {
    id: 5,
    image: imagen5,
    title: "Silla Gamer Genesis RGB Black",
    price: 134.999
  },
  {
    id: 6,
    image: imagen6,
    title: "Fury Thunderstreak Combo",
    price: 11.834
  },
  {
    id: 7,
    image: imagen7,
    title: "Auricular Genesis Neon 750 Rgb Black",
    price: 21.253
  }
];