import { imagen1, imagen2, imagen3, imagen4, imagen5, imagen6, imagen7 } from "../helpers/Index";

export const mockData = [
  {
    "id": 1,
    "image": imagen1,
    "title": "Micro Amd Ryzen 7 5700g 4.6 Ghz Am4",
    "price": 155255,
    "category": "Procesadores"
  },
  {
    "id": 2,
    "image": imagen2,
    "title": "Micro Intel I9-11700kf 5.0ghz 16mb s.1200",
    "price": 221674,
    "category": "Procesadores"
  },
  {
    "id": 3,
    "image": imagen3,
    "title": "Micro Amd Ryzen 9 5900x 4.8 Ghz Am4",
    "price": 298315,
    "category": "Procesadores"
  },
  {
    "id": 4,
    "image": imagen4,
    "title": "Monitor LED CURVO 24 Samsung",
    "price": 108823,
    "category": "Monitores"
  },
  {
    "id": 5,
    "image": imagen5,
    "title": "Silla Gamer Genesis RGB Black",
    "price": 134999,
    "category": "Sillas"
  },
  {
    "id": 6,
    "image": imagen6,
    "title": "Fury Thunderstreak Combo",
    "price": 11834,
    "category": "Combos"
  },
  {
    "id": 7,
    "image": imagen7,
    "title": "Auricular Genesis Neon 750 Rgb Black",
    "price": 21253,
    "category": "Auriculares"
  }
]